# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
script:
- xctool -project CSSwift.xcodeproj -scheme CSSwift-iOS test -sdk iphonesimulator
- xctool -project CSSwift.xcodeproj -scheme CSSwift test -sdk macosx
- xctool -project CSSwift.xcodeproj -scheme CSSwift-tvOS test -sdk appletvsimulator